# Generated by Django 2.1.5 on 2019-04-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=11, null=True, verbose_name='文章标题')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('classify_name', models.CharField(max_length=11, null=True, unique=True, verbose_name='分类标题')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gavin.Classify', verbose_name='所属分类'),
        ),
    ]
