# Generated by Django 2.1.5 on 2019-04-25 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gavin', '0002_auto_20190425_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='文章内容'),
            preserve_default=False,
        ),
    ]
