# Generated by Django 2.1.5 on 2019-04-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gavin', '0003_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
