# Generated by Django 2.1.5 on 2019-04-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gavin', '0004_remove_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='文章内容'),
        ),
    ]
