# Generated by Django 2.1.5 on 2019-04-25 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gavin', '0005_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='classify',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
