# Generated by Django 2.1.5 on 2019-04-25 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gavin', '0006_classify_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
