# Generated by Django 2.1.5 on 2019-04-25 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gavin', '0007_auto_20190425_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/avatars/moren.jpg', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='telephone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
