# Generated by Django 2.1.5 on 2019-04-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gavin', '0009_auto_20190425_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classify',
            name='user',
        ),
    ]
