# Generated by Django 2.1.5 on 2019-04-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gavin', '0010_remove_classify_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
