# Generated by Django 2.1.5 on 2019-04-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gavin', '0014_article_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('comment_name', models.CharField(max_length=11, null=True, verbose_name='评论名')),
                ('comment_content', models.TextField(null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gavin.Article', verbose_name='所属文章')),
            ],
        ),
    ]
